name: "JFrog-GitHub NPM Publish OIDC Integration"

on:
  workflow_dispatch:
  push:
    branches:
      - dev-FB-oidc-poc
      - main

permissions:
  id-token: write

jobs:
  build:
    runs-on: self-hosted
    env:
      OIDC_AUDIENCE: 'frog-company'
      OIDC_PROVIDER: 'jeremyl-frog'
      RELEASE_REPO: 'jl-npm-releases-local'
      DEV_REPO: 'jl-npm-dev-local'
      JF_URL: ${{ secrets.CLOUD_JF_URL }}
    defaults:
      run:
        working-directory: ./package

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node npm
        uses: actions/setup-node@v3

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4.5.6
        with:
          oidc-provider-name: ${{ env.OIDC_PROVIDER }}
          oidc-audience: ${{ env.OIDC_AUDIENCE }}
        env:
          JF_URL: ${{ env.JF_URL }}

      - name: Determine target repo
        id: repo
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "PLATFORM_REPO=${{ env.RELEASE_REPO }}" >> $GITHUB_ENV
          else
            echo "PLATFORM_REPO=${{ env.DEV_REPO }}" >> $GITHUB_ENV
          fi

      - name: Set CLI Config
        run: |
          jf npm-config \
            --repo-resolve=$PLATFORM_REPO \
            --repo-deploy=$PLATFORM_REPO \
            --server-id-resolve setup-jfrog-cli-server \
            --server-id-deploy setup-jfrog-cli-server

      - name: Show RT Servers and Set default
        run: jf c use setup-jfrog-cli-server

      - name: Install Dependencies
        run: jf npm install

      - name: Publish with deployed-by property
        run: |
          COMMITTER=$(git log -1 --pretty=format:'%an')
          jf rt u "package/*.tgz" "$PLATFORM_REPO/" \
            --props "deployed-by=${COMMITTER}"

      - name: Publish Build info With JFrog CLI
        run: |
          jf rt build-collect-env
          jf rt build-add-git
          jf rt build-publish
